### PR TITLE
Fixed Merge Conflict

### PR DESCRIPTION
**Pull request by n-aggarwal**

### CODE REVIEW

**Comment by n-aggarwal** [comment]
@ananafrida please pull this in...

**Comment by ananafrida** [comment]
@n-aggarwal done

**Comment by ananafrida** [comment]
@n-aggarwal I hurriedly pulled the request and didn't check it bc you said over text that the app is fully functional in frontend based on your code. But now that I am running it locally I realized the frontend still doesn't work. You also deleted my update, delete, and create (which is fine as long as the app works.) But the app doesn't work fully. Could you please update asap on what is going on here?

**Comment by ananafrida** [comment]
also if you don't have the fully functional app, I do have it so I can just push it. But please let me know.

**Pull request merged**
